# Server
server.port=8081

# MongoDB Atlas
# Database එක විදිහට 'smartcampus' භාවිතා වේ
spring.data.mongodb.uri=mongodb+srv://admin:admin@cluster0.yzvhd2j.mongodb.net/smartcampus?retryWrites=true&w=majority&appName=Cluster0

# OAuth2 Google
# මෙහි අගට .apps.googleusercontent.com කොටස එක් කර ඇත
spring.security.oauth2.client.registration.google.client-id=193291010316-m148ct3cu7kmsfdbmnbnudkh0ekb6hvg.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# JWT Configuration
jwt.secret=smartcampus-secret-key-2026-very-long-secure-string-min-256bits-extra-safe
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.sliit.paf=DEBUG